// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

/*******************************************************************************
  88888888888 888      d8b                .d888 d8b 888               d8b
      888     888      Y8P               d88P"  Y8P 888               Y8P
      888     888                        888        888
      888     88888b.  888 .d8888b       888888 888 888  .d88b.       888 .d8888b
      888     888 "88b 888 88K           888    888 888 d8P  Y8b      888 88K
      888     888  888 888 "Y8888b.      888    888 888 88888888      888 "Y8888b.
      888     888  888 888      X88      888    888 888 Y8b.          888      X88
      888     888  888 888  88888P'      888    888 888  "Y8888       888  88888P'
                                                        888                 888
                                                        888                 888
                                                        888                 888
     .d88b.   .d88b.  88888b.   .d88b.  888d888 8888b.  888888 .d88b.   .d88888
    d88P"88b d8P  Y8b 888 "88b d8P  Y8b 888P"      "88b 888   d8P  Y8b d88" 888
    888  888 88888888 888  888 88888888 888    .d888888 888   88888888 888  888
    Y88b 888 Y8b.     888  888 Y8b.     888    888  888 Y88b. Y8b.     Y88b 888
     "Y88888  "Y8888  888  888  "Y8888  888    "Y888888  "Y888 "Y8888   "Y88888
         888
    Y8b d88P
     "Y88P"
*******************************************************************************/

#pragma once

#ifndef DIODE_DIRECTION
#    define DIODE_DIRECTION ROW2COL
#endif // DIODE_DIRECTION

#ifndef DYNAMIC_KEYMAP_EEPROM_MAX_ADDR
#    define DYNAMIC_KEYMAP_EEPROM_MAX_ADDR 2047
#endif // DYNAMIC_KEYMAP_EEPROM_MAX_ADDR

#ifndef LED_CAPS_LOCK_PIN
#    define LED_CAPS_LOCK_PIN A7
#endif // LED_CAPS_LOCK_PIN

#ifndef LED_PIN_ON_STATE
#    define LED_PIN_ON_STATE 1
#endif // LED_PIN_ON_STATE

#ifndef PRODUCT_ID
#    define PRODUCT_ID 0x0280
#endif // PRODUCT_ID

#ifndef VENDOR_ID
#    define VENDOR_ID 0x3434
#endif // VENDOR_ID

#ifndef PRODUCT
#    define PRODUCT "Keychron K8 Pro"
#endif // PRODUCT

#ifndef MANUFACTURER
#    define MANUFACTURER "Keychron"
#endif // MANUFACTURER

#ifndef DEVICE_VER
#    define DEVICE_VER 0x0100
#endif // DEVICE_VER

#ifndef MATRIX_COLS
#    define MATRIX_COLS 17
#endif // MATRIX_COLS

#ifndef MATRIX_ROWS
#    define MATRIX_ROWS 6
#endif // MATRIX_ROWS

#ifndef MATRIX_COL_PINS
#    define MATRIX_COL_PINS { B0, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN, NO_PIN }
#endif // MATRIX_COL_PINS

#ifndef MATRIX_ROW_PINS
#    define MATRIX_ROW_PINS { B5, B4, B3, A15, A14, A13 }
#endif // MATRIX_ROW_PINS

#ifndef ENABLE_RGB_MATRIX_BREATHING
#    define ENABLE_RGB_MATRIX_BREATHING
#endif // ENABLE_RGB_MATRIX_BREATHING

#ifndef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#    define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#endif // ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL

#ifndef ENABLE_RGB_MATRIX_CYCLE_ALL
#    define ENABLE_RGB_MATRIX_CYCLE_ALL
#endif // ENABLE_RGB_MATRIX_CYCLE_ALL

#ifndef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#    define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#endif // ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT

#ifndef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#    define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#endif // ENABLE_RGB_MATRIX_CYCLE_UP_DOWN

#ifndef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#    define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#endif // ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON

#ifndef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#endif // ENABLE_RGB_MATRIX_CYCLE_OUT_IN

#ifndef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#    define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#endif // ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL

#ifndef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#    define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#endif // ENABLE_RGB_MATRIX_CYCLE_PINWHEEL

#ifndef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#    define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#endif // ENABLE_RGB_MATRIX_CYCLE_SPIRAL

#ifndef ENABLE_RGB_MATRIX_DUAL_BEACON
#    define ENABLE_RGB_MATRIX_DUAL_BEACON
#endif // ENABLE_RGB_MATRIX_DUAL_BEACON

#ifndef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#    define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#endif // ENABLE_RGB_MATRIX_RAINBOW_BEACON

#ifndef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#    define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#endif // ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS

#ifndef ENABLE_RGB_MATRIX_PIXEL_RAIN
#    define ENABLE_RGB_MATRIX_PIXEL_RAIN
#endif // ENABLE_RGB_MATRIX_PIXEL_RAIN

#ifndef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#    define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#endif // ENABLE_RGB_MATRIX_TYPING_HEATMAP

#ifndef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#    define ENABLE_RGB_MATRIX_DIGITAL_RAIN
#endif // ENABLE_RGB_MATRIX_DIGITAL_RAIN

#ifndef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#endif // ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE

#ifndef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#endif // ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE

#ifndef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#    define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#endif // ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS

#ifndef ENABLE_RGB_MATRIX_SPLASH
#    define ENABLE_RGB_MATRIX_SPLASH
#endif // ENABLE_RGB_MATRIX_SPLASH

#ifndef ENABLE_RGB_MATRIX_SOLID_SPLASH
#    define ENABLE_RGB_MATRIX_SOLID_SPLASH
#endif // ENABLE_RGB_MATRIX_SOLID_SPLASH
